language: python
python:
    - '3.8'

branches:
    only:
    - master

before_script:
    - pip install -r requirements.txt

services:
    - postgresql

env: DJANGO_SETTINGS_MODULE=pur_beurre.settings.travis

script:
    - python manage.py test


